---
title: "Introducton to RcollectlWorkflowh5ad"
output:
  BiocStyle::html_document
vignette: >
  %\VignetteIndexEntry{Introduction to RcollectlWorkflowh5ad}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Rcollectl Workflow

The vignettes in this package follows single-cell analysis workflow (workflow chapters of the “Orchestrating Single-Cell Analysis with Bioconductor” book) to analyze h5ad file from cellxgene dataset and tracks computing resources usage with R package `Rcollectl`.

Two workflows Rcollectlworkflowh5ad and workflow_h5ad_DelayedArray_parameters are available at Dockstore, also set up on Terra workspace,  bioconductor-rpci-yubo/Rcollectlworkflowh5ad. 

Vignette terra_data_import.Rmd includes R code for importing data of h5ad file(s) to Terra workspace to run the workflows. And performance_summary.Rmd provides a performance summary of running the two workflows, functions summary_result_dataset() and summary_result() generate the csv files needed for this vignette.